Dockerized deployment
decred/bitcore-wallet-service pull request #12
Opened 2017-06-15 15:24 UTC by peterzen

Docker configuration for running BWS using docker & docker-compose

2017-07-21 15:32 UTC, jcvernaleo requested changes
Trying to build this failed for me:
```
jcv@triforce bitcore-wallet-service $ docker build -t bws .
Sending build context to Docker daemon 144.9 MB
Step 1 : FROM ubuntu:trusty
...
Now using node v4.2.1 (npm v2.14.7)
Creating default alias: default -> v4.2.1
Now using node v4.2.1 (npm v2.14.7)
npm WARN package.json bitcore-wallet-service@1.9.0 No license field.
npm ERR! tar.unpack untar error /home/bws/.npm/nodemailer-sendgrid-transport/0.2.0/package.tgz
npm ERR! tar.unpack untar error /home/bws/.npm/proxyquire/1.8.0/package.tgz
npm ERR! tar.unpack untar error /home/bws/.npm/bitcore-lib/0.13.16/package.tgz
npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/home/bws/.nvm/versions/node/v4.2.1/bin/node" "/home/bws/.nvm/versions/node/v4.2.1/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /home/bws/app/node_modules/nodemailer-sendgrid-transport
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/home/bws/app/node_modules/nodemailer-sendgrid-transport'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/home/bws/app/node_modules/nodemailer-sendgrid-transport']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/bws/app/node_modules/nodemailer-sendgrid-transport',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/home/bws/app/node_modules/nodemailer-sendgrid-transport',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/home/bws/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/home/bws/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, rmdir '/home/bws/app/node_modules/crypto-browserify'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, rmdir '/home/bws/app/node_modules/crypto-browserify']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/bws/app/node_modules/crypto-browserify' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bws/app/npm-debug.log
The command '/bin/sh -c curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash &&     . $NVM_DIR/nvm.sh &&     nvm install $NODE_VERSION &&     nvm use $NODE_VERSION &&     npm install' returned a non-zero code: 243
jcv@triforce bitcore-wallet-service $ ls
```

2017-07-21 15:32 UTC, jcvernaleo commented on Dockerfile
> +RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash && \
As mentioned in similar PRs, I'd really rather a git checkout followed by running a command rather than piping the output of curl straight to bash.

2017-07-21 15:32 UTC, jcvernaleo commented on Dockerfile
> +FROM ubuntu:trusty
I like the intended name as a comment on the top.

2017-07-22 12:45 UTC, peterzen commented on Dockerfile
> +FROM ubuntu:trusty
Added the comment.

2017-07-22 12:49 UTC, peterzen commented
I've made the nvm change, thanks for spotting that.  The build error I can't reproduce for some reason, it runs cleanly on my end but will look into it more as I'm getting a different but potentially related runtime error when using my [docker-compose](https://github.com/peterzen/decred-bws-backend) setup to launch the stack.

2017-07-24 11:28 UTC, jcvernaleo commented
So I can't hit the build error any more.  Must have been something transient for me (some download failing or something).

2017-07-24 11:29 UTC, jcvernaleo commented
Are you still working on the docker-compose issue or is this ready?  Looking good to me otherwise.

2017-07-24 11:56 UTC, peterzen commented
This should be ready – the compose issue has to be fixed in the other repo.

2017-07-24 13:06 UTC, jcvernaleo commented
I still prefer the model of docker files going in one repo and directly including the files they will server (by git hash) leaving as little as possible on the host but I understand that is only good for pure deploy situations.  Since this seems to be dev and deploy I understand the preference for doing it this way.

I'm fine with this but since @dajohi and @alexlyp are more directly involved with deploy I'll leave the actual merging to them (to give them a chance to comment if they want).  But nice job!

2017-07-24 13:06 UTC, jcvernaleo approved these changes

2018-01-02 19:43 UTC, dajohi approved these changes
ok

2018-01-02 19:44 UTC, merged